/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uis.maps;

import uis.tile.Tile;
import uis.tile.TileEnum;
import java.util.HashMap;
import javafx.scene.image.Image;

/**
 *
 * @author Jonathan
 */
public class BackgroundMap {
    
    static HashMap<String, Image> levelMap;
    
    public BackgroundMap() {
        levelMap = new HashMap<>();
        
//        levelMap.put("00", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("01", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("02", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("03", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("04", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("05", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("06", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("07", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("08", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("09", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("10", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("11", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("12", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("13", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("14", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("15", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("16", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("17", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("18", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("19", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("20", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("21", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("22", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("23", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("24", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("25", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("26", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("27", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("28", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("29", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("30", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("31", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("32", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("33", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("34", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("35", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("36", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("37", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("38", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("39", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("40", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("41", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("42", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("43", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("44", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("45", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("46", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("47", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("48", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("49", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("50", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("51", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("52", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("53", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("54", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("55", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("56", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("57", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("58", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("59", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("60", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("61", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("62", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("63", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("64", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("65", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("66", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("67", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("68", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("69", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("70", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("71", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("72", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("73", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("74", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("75", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("76", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("77", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("78", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("79", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("80", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("81", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("82", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("83", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("84", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("85", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("86", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("87", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("88", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("89", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("90", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("91", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("92", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("93", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("94", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("95", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("96", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("97", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("98", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("99", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("100", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("101", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("102", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("103", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("104", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("105", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("106", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("107", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("108", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("109", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("110", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("111", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("112", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("113", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("114", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("115", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("116", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("117", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("118", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("119", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("120", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("121", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("122", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("123", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("124", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("125", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("126", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("127", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("128", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("129", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("130", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("131", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("132", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("133", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("134", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("135", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("136", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("137", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("138", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("139", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("140", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("141", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("142", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("143", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("144", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("145", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("146", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("147", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("148", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("149", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("150", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("151", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("152", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("153", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("154", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("155", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("156", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("157", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("158", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("159", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("160", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("161", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("162", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("163", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("164", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("165", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("166", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("167", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("168", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("169", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("170", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("171", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("172", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("173", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("174", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("175", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("176", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("177", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("178", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("179", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("180", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("181", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("182", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("183", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("184", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("185", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("186", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("187", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("188", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("189", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("190", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("191", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("192", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("193", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("194", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("195", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("196", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("197", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("198", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("199", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("010", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("011", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("012", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("013", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("014", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("015", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("016", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("017", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("018", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("019", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("110", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("111", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("112", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("113", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("114", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("115", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("116", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("117", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("118", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("119", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("210", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("211", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("212", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("213", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("214", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("215", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("216", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("217", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("218", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("219", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("310", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("311", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("312", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("313", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("314", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("315", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("316", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("317", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("318", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("319", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("410", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("411", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("412", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("413", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("414", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("415", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("416", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("417", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("418", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("419", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("510", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("511", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("512", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("513", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("514", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("515", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("516", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("517", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("518", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("519", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("610", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("611", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("612", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("613", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("614", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("615", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("616", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("617", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("618", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("619", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("710", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("711", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("712", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("713", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("714", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("715", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("716", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("717", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("718", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("719", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("810", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("811", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("812", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("813", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("814", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("815", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("816", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("817", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("818", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("819", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("910", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("911", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("912", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("913", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("914", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("915", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("916", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("917", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("918", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("919", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("1010", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1011", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1012", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1013", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1014", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1015", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1016", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1017", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1018", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1019", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("1110", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1111", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1112", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1113", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1114", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("1115", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1116", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1117", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1118", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1119", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("1210", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1211", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1212", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1213", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1214", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1215", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("1216", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1217", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1218", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1219", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("1310", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1311", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1312", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1313", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("1314", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1315", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1316", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1317", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1318", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1319", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("1410", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1411", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1412", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1413", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1414", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1415", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("1416", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("1417", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1418", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1419", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("1510", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1511", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1512", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1513", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("1514", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1515", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1516", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1517", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1518", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1519", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("1610", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1611", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1612", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1613", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1614", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("1615", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1616", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1617", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1618", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1619", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("1710", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1711", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1712", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1713", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1714", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1715", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1716", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1717", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("1718", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1719", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("1810", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1811", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1812", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("1813", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1814", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1815", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1816", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1817", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1818", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1819", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("1910", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1911", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1912", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1913", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1914", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1915", new Image(TileEnum.BACKGROUND.toString()));
//        levelMap.put("1916", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1917", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1918", new Image(TileEnum.BACKGROUND.toString()));
        levelMap.put("1919", new Image(TileEnum.BACKGROUND.toString()));
    }
    
    public static HashMap getMap() {
        return levelMap;
    }
}
